
#! /bin/bash

TILE_GENERATOR_SCRIPT_PATH=${1}
MAP_DIRECTORY=${2}
TEMP_IMAGE_PATH=${3}
IMAGE_EXTENSION=${4}



mkdir -p ${MAP_DIRECTORY}
python3 ${TILE_GENERATOR_SCRIPT_PATH} -l -p raster -w none ${TEMP_IMAGE_PATH} ${MAP_DIRECTORY}
cp ${TEMP_IMAGE_PATH} ${MAP_DIRECTORY}/original.${IMAGE_EXTENSION}
