<?php
/*
 *
 * This is the default blog post template
 *
 */
require_once __DIR__ . '/../inc/above.php';

// Page-specific preparatory code goes here.

$postContent = str_replace( ']]>', ']]&gt;', apply_filters( 'the_content', $thePost[ 'post_content' ] ) );

?>





<!-- Blog Page -->
<section class="blog-page">
	<div class="blog-header fill-dark">
		<div class="container">
			<div class="row">
				<div class="columns small-12">
					<div class="logo"><a href="<?php echo $baseURL ?>" class="inline"><img class="block" src="../media/indis-logo-light.svg<?php echo $ver ?>"></a></div>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="columns small-12 large-10 xlarge-9">
				<div class="blog-title h1 strong text-lowercase space-50-top-bottom"><?= $thePost[ 'post_title' ] ?></div>
			</div>
			<div class="columns small-12 large-9 xlarge-8">
				<div class="blog-content"><?= $postContent ?></div>
			</div>
		</div>
	</div>
</section>

<script type="text/javascript">

	/*
	 * ----- Gallery Carousel
	 *
	 * Galleries created by Gutenberg have the classname `blocks-gallery-grid`
	 *
	 * Assign `data-gallery` attribute, and add classes to all the galleries on the page (generated by Gutenberg)
	 * Initialise the carousel
	 *
	 */
	$( function () {

		// If no galleries are on the page, return
		if ( ! $( ".blocks-gallery-grid" ).length )
			return;

		// Set ids for the galleries
		$( ".blocks-gallery-grid" ).each( function ( _i, el ) {
			$( el ).attr( "data-gallery", "gallery-reel-" + ( _i + 1 ) );
		} );
		// Add classes to the galleries
		$( ".blocks-gallery-item img" )
			.addClass( "js_gallery_item js_modal_trigger" )
			.attr( "data-mod-id", "image-gallery" );

		// Initialise the carousel
		$( ".blocks-gallery-grid" ).slick( {
			arrows: true,
			dots: false,
			infinite: true,
			speed: 800,
			autoplaySpeed: 3000,
			slidesToShow: 1,
			centerMode: true,
			variableWidth: true,
			lazyLoad: "ondemand"
		} ).slickNext();

	} );

</script>
<!-- END: Blog Page -->





<?php require_once __DIR__ . '/../inc/below.php'; ?>
